name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild -project 'CinemaTv.xcodeproj' -scheme 'CinemaTv' -destination 'generic/platform=iOS Simulator,name=iPhone 12' -configuration Release build CODE_SIGNING_ALLOWED=NO
